# Identidad Maestra de RAYO - Stellar BC Corp
NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

[[CURRENCIES]]
code="RAYO"
issuer="GBPDJLJ23JEKXV5VVDD3FVNPW5XRRZPK6PCHWRIKM2STZ57423B6IXSQ"
display_decimals=7
name="RAYO"
desc="Official asset of Stellar BC Corp. High-performance digital currency designed for speed and exclusivity. | Activo oficial de Stellar BC Corp. Dise√±ado para ofrecer velocidad y exclusividad."
image="https://stellar-bc.github.io/congenial/logoderayostellar.png"

[DOCUMENTATION]
ORG_NAME="Stellar BC Corp"
ORG_URL="https://stellar-bc.github.io/congenial"
