# Identidad Maestra de RAYO - Stellar BC Corp
NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

[ORGANIZATION]
NAME="Stellar BC Corp"
URL="https://stellarbccorp.carrd.co/"
LOGO="https://stellar-bc.github.io/congenial/logoderayostellar.png"
DESCRIPTION="High-performance digital currency designed for speed and exclusivity."
TWITTER="https://x.com/JEnriquez345r"

[[CURRENCIES]]
code="RAYO"
issuer="GBPDJLJ23JEKXV5VVDD3FVNPW5XRRZPK6PCHWRIKM2STZ57423B6IXSQ"
display_decimals=7
name="RAYO"
desc="Official asset of Stellar BC Corp. High-performance digital currency designed for speed. | Activo oficial de Stellar BC Corp. Dise√±ado para ofrecer velocidad."
image="https://stellar-bc.github.io/congenial/logoderayostellar.png"
status="live"
anchor_asset_type="other"

[DOCUMENTATION]
ORG_NAME="Stellar BC Corp"
ORG_URL="https://stellarbccorp.carrd.co/"
