NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

[ORGANIZATION]
NAME="Stellar BC Corp"
URL="https://stellarbccorp.carrd.co/"
LOGO="https://stellar-bc.github.io/congenial/logoderayostellar.png"
DESCRIPTION="High-performance digital currency designed for speed and exclusivity."
TWITTER="https://x.com/JEnriquez345r"

[[CURRENCIES]]
code="RAYO"
issuer="GBPDJLJ23JEKXV5VVDD3FVNPW5XRRZPK6PCHWRIKM2STZ57423B6IXSQ"
display_decimals=7
name="RAYO"
desc="System focused on capital reinvestment to ensure ecosystem stability. Stellar BC Corp is committed to a perpetual 70% reinvestment policy of all rewards back into the liquidity pool. | Sistema enfocado en la reinversión de capital para asegurar la estabilidad del ecosistema. Stellar BC Corp se compromete a una política perpetua de reinversión del 70% de todas las recompensas en la pool de liquidez.https://stellarbccorp.carrd.co/ 
image="https://stellar-bc.github.io/congenial/logoderayostellar.png"
status="live"
anchor_asset_type="other"

[DOCUMENTATION]
ORG_NAME="Stellar BC Corp"
ORG_URL="https://stellarbccorp.carrd.co/"
